networks:
  app-network:
    driver: bridge

services:
  frontend:
    build:
      context: apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: apps/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
